ALTER TABLE "Course" 
ALTER COLUMN "Course_ID" ADD GENERATED ALWAYS AS IDENTITY;



ALTER TABLE "Course" ALTER COLUMN "Author_ID" DROP NOT NULL;

ALTER TABLE "Course" ALTER COLUMN "Author_ID" SET DEFAULT 0;



ALTER TABLE "Course" 
DROP CONSTRAINT "Course_Author_ID_fkey";